### ISSUE TITLE
+10% to RealFightTalent each time I learn +1% or 5% in weapon skill.

### ISSUE THREAD

**Issue by Shavier16** [elsky42/ninja-bonus_independent_training#2]
**Hello there.**
Thank you for creating this script. It was annoying that every mod I found, with ability to use stat bonuses instantly, were adding some other stuff I don't want in the game.

Anyway I have a problem that when I learn any weapon skill, "Real" value goes up by additional 10 (ex. 10%/10% becomes 21%/11% then 32%/12% etc.) which makes learning weapon skills to expensive real quick. (On my screenshot I should have 11%/30% 1h).

I tried to fix it myself by reviewing your code, but I didn't find anything wrong and I am not familliar with Ninja2 to be able to change anything really.

All I have installed is your script, Ninja2, Union1.0m (with zBugFixes, zTorchControl, Union_SpellFix), TexturePack by Artemiano, Telekinesis (to find items like in Archolos) and GD3DX11

_PS. Would you be able to make Innos pray bonuses also not count toward "Real" value? They are to useful to wait for the end. 
(20 str and 17 agi are Innos bonus, I play as a mage rn)_
![beforeLP](https://user-images.githubusercontent.com/111721675/185842711-44bddcd2-3230-424f-bf3d-bd56c0fd8e2d.jpg)
![afterLP](https://user-images.githubusercontent.com/111721675/185842718-9621ce69-6431-48b5-8d21-ea7a10964bc3.jpg)

**Comment by elsky42** [comment]
Hey, I tried to reproduce the issue but with no luck. If I train 1h or 2h from Wulfgar, my 10/10 becomes 11/11 if I train 1  or 15/15 if I train 5. I'm genuinely not sure what's going on with your game.

I will make the prayers not count toward the real values as soon as I have some time.

**Comment by Shavier16** [comment]
Ok, did some more testing.

For some reason my char starts with 0%/10% instead 10%/10% (started game without Ninja on my main save, that's why he had 10%/10%) and when I change Fix start with 10, to: "raiseTo = 20 - realTalent + percent" it now adds 20 to "Real" value instead. 

Even changing 'aivar' in console to be 10%/10% doesn't help. Also 20% difference bonus from trainer doesn't add to "Real" value (if it should).

Removed all mods, reinstall Ninja and Union, tried EN version of the game and still same result. 

Gonna try fresh install tomorrow, but after that I give up. At least mage doesn't require a lot of weapon skills.

**Comment by elsky42** [comment]
Hey @Shavier16 , I finally fixed the issue with the shrines pray bonuses. I released v0.7.1 with the fix. I'll have a look again at the issue you have found soon.
