### ISSUE TITLE
Skill training incorrect

### ISSUE THREAD

**Issue by ironbrand** [elsky42/ninja-bonus_independent_training#3]
I trained my 1-handed skill to 31% however the left side value is somehow 81% and the right side is 31%. Editing the skill value via the in game editor only changes the right hand value. LP costs for training match the 81% value

 
![skills](https://user-images.githubusercontent.com/113836451/190900894-4305b4dc-4188-47e0-b19f-c948b6987e13.jpg)

**Comment by elsky42** [comment]
Hi @ironbrand , thanks for reporting the bug. I think this is the same bug as #2 and it got fixed yesterday with the release 0.7.2. Sadly it doesn't work with existing saves. You'll have to start a new game or find a way to fix the wrong values. If you don't find a way then maybe I can add a command to the mod that allows to change those values but I don't know when I'll be able to add it.

**Comment by elsky42** [comment]
Hi @ironbrand , I've released v0.7.3 with a new command `BIT setrealcharactervalue` that allows to change trained values only. Have a [look at the README](https://github.com/elsky42/ninja-bonus_independent_training#commands) to see how to use it. For instance, to reset one-handed to 31 then you can write

```
BIT setrealcharactervalue str 31
```

I hope this helps.
