### ISSUE TITLE
trainer_max_against_effective=false doesn't work

### ISSUE THREAD

**Issue by B2SquareOne** [elsky42/ninja-bonus_independent_training#6]
Hello, its me again :) I'll try to keep it short this time.
Did some testing already and this is where I'm at:
only installed fresh Gothic 2 notr GoG version
+ systempack + latest Union via Ressourcen Manager
+ Ninja
If I use your latest version (which didnt crash in 10h+ gametime btw, fix worked!) the trainer_max_against_effective=false does not seem to work. 
Im at 57 Str and drank 1 Potion of Str for + 3 so = 60. But still Lares who trains until 60 wont train me anymore.

Maybe it's only a small fix..

**Comment by elsky42** [comment]
Hey @B2SquareOne, thanks for reporting this! I will have a look as soon as I have time.

**Comment by elsky42** [comment]
It should be fixed in v0.7.5. Please try with that one and let me know if it works.

**Comment by B2SquareOne** [comment]
Seems good now, works as expected :) Thank you again for you quick help!!!
